### ISSUE TITLE
V1.3.3 not updating

### ISSUE THREAD

**Issue by BoscoRemus** [lindenbergresearch/LRTRack#60]
Red dot for Library, On the Library tab in rack it shows update for v1.3.3 you click on update all. you don't see it extract the file with the countdown. reopen Rack and has not updated still shows the red dot..
I watch the directory from Finder I see the Zip file appear and then disappear and no update.. 
OS: Mac 10.14.6
Rack version: 1.1.6

**Comment by BoscoRemus** [comment]
![Screen Shot 2020-01-30 at 8 51 30 PM](https://user-images.githubusercontent.com/42082512/73513440-56e78d80-43a2-11ea-8b1b-6b3a92e7fea0.png)

**Comment by lindenbergresearch** [comment]
It was a problem with the DB - Andrew fixed this, should work now.

**Comment by Coirt** [comment]
Not fixed on Windows 10 details posted on community https://community.vcvrack.com/t/lindberghresearch-modules-not-updating/7895/23?u=coirt
